[package]
name = "km003c-cli"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"

[dependencies]
km003c-lib = { path = "../km003c-lib" }
tokio = { version = "1.45", features = ["full"] }
clap = { version = "4.0", features = ["derive"] }
tracing-subscriber = "0.3"
tracing = "0.1"
hex = "0.4"
usbpd = { git = "https://github.com/okhsunrog/usbpd", branch = "finished_epr_support" }
uom = "0.36"
